Underwater_SeafloorCavern:
	.4byte Underwater_SeafloorCavern_Layout
	.4byte Underwater_SeafloorCavern_MapEvents
	.4byte Underwater_SeafloorCavern_MapScripts
	.4byte 0x0
	.2byte MUS_DEEPDEEP
	.2byte LAYOUT_UNDERWATER_SEAFLOOR_CAVERN
	.byte MAPSEC_UNDERWATER_128
	.byte 0
	.byte WEATHER_UNDERWATER_BUBBLES
	.byte MAP_TYPE_UNDERWATER
	.2byte 0
	map_header_flags allow_cycling=1, allow_escaping=0, allow_running=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL

