UnknownLinkContestRoom_25_33:
	.4byte UnknownLinkContestRoom_25_33_Layout
	.4byte ContestHall_MapEvents
	.4byte ContestHall_MapScripts
	.4byte 0x0
	.2byte MUS_NIBI
	.2byte LAYOUT_UNKNOWN_LINK_CONTEST_ROOM_25_33
	.byte MAPSEC_DYNAMIC
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_cycling=0, allow_escaping=0, allow_running=0, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

