Underwater3:
	.4byte Underwater3_Layout
	.4byte Underwater3_MapEvents
	.4byte Underwater3_MapScripts
	.4byte Underwater3_MapConnections
	.2byte MUS_DEEPDEEP
	.2byte LAYOUT_UNDERWATER3
	.byte MAPSEC_UNDERWATER_126
	.byte 0
	.byte WEATHER_UNDERWATER_BUBBLES
	.byte MAP_TYPE_UNDERWATER
	.2byte 0
	map_header_flags allow_cycling=1, allow_escaping=0, allow_running=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL

