BattleFrontier_BattlePikeCorridor:
	.4byte BattleFrontier_BattlePikeCorridor_Layout
	.4byte BattleFrontier_BattlePikeCorridor_MapEvents
	.4byte BattleFrontier_BattlePikeCorridor_MapScripts
	.4byte 0x0
	.2byte MUS_B_TUBE
	.2byte LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR
	.byte MAPSEC_BATTLE_FRONTIER
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_INDOOR
	.2byte 0
	map_header_flags allow_cycling=0, allow_escaping=0, allow_running=1, show_map_name=0
	.byte MAP_BATTLE_SCENE_NORMAL

