CaveOfOrigin_UnusedRubySapphireMap3:
	.4byte CaveOfOrigin_UnusedRubySapphireMap3_Layout
	.4byte CaveOfOrigin_UnusedRubySapphireMap3_MapEvents
	.4byte CaveOfOrigin_UnusedRubySapphireMap3_MapScripts
	.4byte 0x0
	.2byte MUS_DAN03
	.2byte LAYOUT_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3
	.byte MAPSEC_CAVE_OF_ORIGIN
	.byte 1
	.byte WEATHER_FOG_HORIZONTAL
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL

