CaveOfOrigin_UnusedRubySapphireMap1:
	.4byte CaveOfOrigin_UnusedRubySapphireMap1_Layout
	.4byte CaveOfOrigin_UnusedRubySapphireMap1_MapEvents
	.4byte CaveOfOrigin_UnusedRubySapphireMap1_MapScripts
	.4byte 0x0
	.2byte MUS_DAN03
	.2byte LAYOUT_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1
	.byte MAPSEC_CAVE_OF_ORIGIN
	.byte 1
	.byte WEATHER_NONE
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_NORMAL

