AquaHideout_UnusedRubyMap1:
	.4byte AquaHideout_UnusedRubyMap1_Layout
	.4byte AquaHideout_UnusedRubyMap1_MapEvents
	.4byte AquaHideout_UnusedRubyMap1_MapScripts
	.4byte 0x0
	.2byte MUS_AJITO
	.2byte LAYOUT_AQUA_HIDEOUT_UNUSED_RUBY_MAP1
	.byte MAPSEC_AQUA_HIDEOUT
	.byte 0
	.byte WEATHER_NONE
	.byte MAP_TYPE_UNDERGROUND
	.2byte 0
	map_header_flags allow_cycling=1, allow_escaping=1, allow_running=1, show_map_name=1
	.byte MAP_BATTLE_SCENE_MAGMA

